### ISSUE TITLE
Feature request: Be able to run query directly from either Vision or GROQ Snippet page.

### ISSUE THREAD

**Issue by wbern** [williamiommi/sanity-plugin-groq-snippet#7]
Maybe I'm missing something, but it would be great if I could just click a button "Execute query" or something.

What do you think?

**Comment by williamiommi** [comment]
Hi @wbern,

The idea of the plugin is to store Groq snippets only. I prefer to leave the execution of the queries to the official plugin. 
But I understand your point. After some investigation on how Vision stores the last executed query, I found a possible new feature to add. It will not execute the query, but by clicking on a 'Load it on Vision" button, it will redirect you to the Vision plugin (if available) with your query (and parameters) preloaded. From here, you can click Vision's 'Run' button to execute the query.

It's not a 'one-click' feature, but it's better than nothing. Currently, I haven't found a proper way to interact with the 'Execute' button after landing on the Vision page.

**Comment by wbern** [comment]
I would say that's exactly how I'd like it to work. 😊😊

**Comment by williamiommi** [comment]
New feature released 😃

**Comment by wbern** [comment]
You're awesome!

Gonna try it out next week for sure. ❤️

**Comment by wbern** [comment]
Any idea where I can find the button to run it? :-D

![image](https://github.com/williamiommi/sanity-plugin-groq-snippet/assets/25477382/7b30adda-ad4f-45a4-b5ab-8a710402e3db)

Also, I noticed you wrote in the readme that it can be executed inside the edit button, perhaps we could move it as a button to the listings page for easier execution?

**Comment by williamiommi** [comment]
Hi @wbern,

that's nice :D...yes, the button should be near the 'Update snippet'.
Did you change the name of your Vision tool? Your vision tool is reachable at the following path '/vision' or something else?

**Comment by wbern** [comment]
The url is /vision

![image](https://github.com/williamiommi/sanity-plugin-groq-snippet/assets/25477382/27886c0a-e55c-4e5c-abbf-cf0c41207ecd)

Is this correct?

I just use the plugin without options `GroqSnippetPlugin(), in sanity config.

**Comment by williamiommi** [comment]
yes, should be fine, it's the default name of the vision tool.
The version of the plugin on your package.json is '1.1.0' right?

I will do a check this evening anyway.
I'll keep you posted.

**Comment by wbern** [comment]
OK, when I deleted the `.sanity` cache folder and updated sanity dependencies, it started to work (not sure if I had to update the deps).

It works really well. Thanks!!!

**Comment by williamiommi** [comment]
Awesome!!! Glad it worked.
